### ISSUE TITLE
fails to build, new owncloud needs PHP 5.4.0

### ISSUE THREAD

**Issue by JasonBoyles** [rackspace-orchestration-templates/owncloud#8]
Install completes successfully, but tests fail because owncloud shows this error on page load:

```html
This version of ownCloud requires at least PHP 5.4.0
<br/>
You are currently running 5.3.10-1ubuntu3.16. Please update your PHP version. 
```

**Comment by JasonBoyles** [comment]
We may be able to get PHP 5.4.0 on 12.04 using the repo described here:

http://www.barryodonovan.com/2012/05/22/ubuntu-12-04-precise-pangolin-and-php-5-4-again

**Comment by JasonBoyles** [comment]
This is cheating, and doesn't solve the ultimate problem, which is that we need to be on Ubuntu 14.04, but this cloud-init data will ensure that php5 gets installed at 5.4.x on the server:

```yaml
#cloud-config
apt_sources:
 - source: "ppa:ondrej/php5-oldstable"
package_update: true
```
